### ISSUE TITLE
Any updates yet about the code release?

### ISSUE THREAD

**Issue by funcdecl** [HKUST-3DV/DIM-SLAM#6]
Thank you for your great job！
When will this source code open？

**Comment by poptree** [comment]
Hi, 
I am really busy in the previous months. I will release the code of the frame selection after implementation.

Since the code of SFM and  local windows selection is already released, you can also adopt the global keyframe selection from NICE-SLAM, to form the whole system. You only need to add a pixel flow to check whether a frame is a keyframe or not. Most tech details are included in the main paper and the openreview.

Hope the suggestion will be helpful.
